[2024-04-06T04:15:32.841+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 20020541.2054 manual__2024-04-06T04:15:28.924598+00:00 [queued]>
[2024-04-06T04:15:32.862+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 20020541.2054 manual__2024-04-06T04:15:28.924598+00:00 [queued]>
[2024-04-06T04:15:32.865+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-06T04:15:32.892+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2054> on 2024-04-06 04:15:28.924598+00:00
[2024-04-06T04:15:32.901+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2024-04-06T04:15:32.921+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '20020541', '2054', 'manual__2024-04-06T04:15:28.924598+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpp9186jl8']
[2024-04-06T04:15:32.929+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask 2054
[2024-04-06T04:15:33.007+0000] {task_command.py:423} INFO - Running <TaskInstance: 20020541.2054 manual__2024-04-06T04:15:28.924598+00:00 [running]> on host 13802dcf9dcd
[2024-04-06T04:15:33.120+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='20020541' AIRFLOW_CTX_DAG_ID='20020541' AIRFLOW_CTX_TASK_ID='2054' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T04:15:28.924598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-06T04:15:28.924598+00:00'
[2024-04-06T04:15:33.145+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 404 (Not Found)\nRaw response content:\nb\'{"status":{"error":"Not found: Collection `20020541` doesn\\\'t exist!"},"time":0.000078958}\''}
[2024-04-06T04:15:33.161+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=20020541, task_id=2054, execution_date=20240406T041528, start_date=20240406T041532, end_date=20240406T041533
[2024-04-06T04:15:33.189+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-06T04:15:33.216+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
