[2024-04-06T03:59:07.459+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 20020541.2054 scheduled__2024-04-06T03:39:34.135167+00:00 [queued]>
[2024-04-06T03:59:07.528+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 20020541.2054 scheduled__2024-04-06T03:39:34.135167+00:00 [queued]>
[2024-04-06T03:59:07.530+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-06T03:59:07.737+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2054> on 2024-04-06 03:39:34.135167+00:00
[2024-04-06T03:59:07.832+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-04-06T03:59:07.951+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '20020541', '2054', 'scheduled__2024-04-06T03:39:34.135167+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmphz7z_0hl']
[2024-04-06T03:59:07.966+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask 2054
[2024-04-06T03:59:08.488+0000] {task_command.py:423} INFO - Running <TaskInstance: 20020541.2054 scheduled__2024-04-06T03:39:34.135167+00:00 [running]> on host ef7ef7508ab8
[2024-04-06T03:59:09.268+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='20020541' AIRFLOW_CTX_DAG_ID='20020541' AIRFLOW_CTX_TASK_ID='2054' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T03:39:34.135167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T03:39:34.135167+00:00'
[2024-04-06T03:59:09.866+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 404 (Not Found)\nRaw response content:\nb\'{"status":{"error":"Not found: Collection `20020541` doesn\\\'t exist!"},"time":0.004598042}\''}
[2024-04-06T03:59:10.049+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=20020541, task_id=2054, execution_date=20240406T033934, start_date=20240406T035907, end_date=20240406T035910
[2024-04-06T03:59:10.137+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-06T03:59:10.295+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
