[2024-04-06T03:59:10.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 20020541.2002 scheduled__2024-04-06T03:44:34.135167+00:00 [queued]>
[2024-04-06T03:59:10.320+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 20020541.2002 scheduled__2024-04-06T03:44:34.135167+00:00 [queued]>
[2024-04-06T03:59:10.328+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-06T03:59:10.578+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2002> on 2024-04-06 03:44:34.135167+00:00
[2024-04-06T03:59:10.623+0000] {standard_task_runner.py:60} INFO - Started process 140 to run task
[2024-04-06T03:59:10.634+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '20020541', '2002', 'scheduled__2024-04-06T03:44:34.135167+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpu0ger7ns']
[2024-04-06T03:59:10.639+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask 2002
[2024-04-06T03:59:11.002+0000] {task_command.py:423} INFO - Running <TaskInstance: 20020541.2002 scheduled__2024-04-06T03:44:34.135167+00:00 [running]> on host ef7ef7508ab8
[2024-04-06T03:59:11.712+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='20020541' AIRFLOW_CTX_DAG_ID='20020541' AIRFLOW_CTX_TASK_ID='2002' AIRFLOW_CTX_EXECUTION_DATE='2024-04-06T03:44:34.135167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-06T03:44:34.135167+00:00'
[2024-04-06T03:59:12.659+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `20020541` already exists!"},"time":0.740767375}\''}
[2024-04-06T03:59:12.803+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=20020541, task_id=2002, execution_date=20240406T034434, start_date=20240406T035910, end_date=20240406T035912
[2024-04-06T03:59:12.986+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-06T03:59:13.078+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
